name: ci

on:
  push:
    branches:
      - main
      - master
    tags:
      - "v*"
    path:
      - "Dockerfile*"
      - ".github/workflows/ci.yml"
  schedule:
    - cron:  '0 0 1 * *'

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12, 14, lts]
        os: [alpine]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Set up QEMU
        if: success()
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        if: success()
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        if: success()
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache/${{ matrix.os }}
          key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile.${{ matrix.os }}') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Registry
        if: success()
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        if: success()
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64
          file: ./Dockerfile.${{ matrix.os }}
          tags: fengsiio/node-dev:${{ matrix.node }}-${{ matrix.os }}
          cache-from: type=local,src=/tmp/.buildx-cache/${{ matrix.os }}
          cache-to: type=local,dest=/tmp/.buildx-cache/${{ matrix.os }},mode=max
